---
version: "3"
services:
  app:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    # working_dir: /app
    # command: ./bin/run
    volumes:
      - ./:/app
    ports:
      - "8501:8501"